# -*- coding: utf-8 -*-
"""firstpgm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zMd4-1hbbnmuzy7IdPfCGCtwWvZgwdG0
"""

print("Hello World")

x=5
y="5.3"
z=True
print("value of x = ", x)
print("value of y = ", y)
print("value of z = ", z)
print(type(x))
print(type(y))
print(type(z))

#comment
'''subtract -
divide -   /
interger - //
power - **
remainder - %'''

x=int(input("enter an integer"))
x = x + 5
print("the value entered is ", x)

x=int(input("enter the first number"))
y=int(input("enter the second number"))
print(x+y)
print(x/y)
print("integer division",x//y)
print("power",x**y)
print("remainder",x%y)

x=int(input())
if(x>0):
    
    print("x is positive")
    if (x%5==0):
        print("x is multiple of 5")
    elif(x%2==0):
        print("x is not a multiple of 5 but multiple of 2")
    else:
        print("neither of 2")
else:
    print("x is 0 or negative")
print("automatically outside if statement")

x=int(input())
if(x>0):
    
    print("x is positive")
    if (x%2==0):
        print("x is even")
    
    else:
        print("x is odd")
else:
    print("x is 0 or negative")

x="5"
print(5*x)

for i in range(5,10):
    print(i)

for i in range(10):
    print(i)

for i in range(5,10,2):
    print(i)

for i in range(10,4,-2):
    print(i)

str1="Hello Bangalore"
for i in str1:
    print(i)

l1=[3,7,3.2,6,1,8]
for i in l1:
    print(i)

a='car'
b='bus'
print('a=', a , " b = ", b)
(a,b)=(b,a)
print('a=', a , " b = ", b)

fruit = "IBM"
print(type(fruit))
print(dir(fruit))

fruit="orange"
print(fruit)
letter = fruit[0]
print(letter)
print(fruit[4])
length=len(fruit)
print(length)
for i in fruit:
    print(i,end=" ")
    
print("the length of the string is ",len(fruit))

s = 'abcdefghijklmn'
#    0 2 4 6 8  
print(s[0:5])
print(s[6:12:2])
print(s[0:3])
print(s[3:])
print(s[8:3:-1]) 
print(s[::2])
print(s[::-1])
print(s[-1])
print(s[-2])
print(s[-10])
print(s[-15:])

# define punctuation
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
# To take input from the user
my_str = input("Enter a string: ")
# remove punctuation from the string
no_punct = ""
for char in my_str:
    if char not in punctuations:
        no_punct = no_punct + char
# display the unpunctuated string
print(no_punct)

x = [2, 'a', 4.5, False]
print(x)
print(type(x))
print(type(x[1]))
print(x[1:3])

l1=list(range(1,20,2))
print(l1)
l1.insert(2,99)
print(l1)
l1.append('IBM')
print(l1)
l1.extend('IBM')
print(l1)

list1 = [23,56,23,58,23,89,45,23]
count = 0
for i in list1:
    if (i==23):
        count=count+1
print("Total count of 23 num=",count)

x=int(input())
print("even") if(x%2==0) else print("odd")

#Creating key value pairs, a dictionary
#flower brackets
x = {"Kar": "blr", 
     "TN": "Chn", 
     "Mah": "Mum"}
print(x)
x["Ker"] = "Tvm"
x["AP"] = "Hyd"
print(x)
x["Kar"] = "Bangalore"
x["AP"] = "Hyderabad"
print(x)